theme: minimal-mistakes-jekyll
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag

title: "Apis Library"
description: "Arduino library for the Apis LiDAR rangefinder board"
baseurl: "/Apis_Library"
url: "https://docs.northernwidget.com"
permalink: /:path/

minimal_mistakes_skin: "default"

author:
  name: "Northern Widget"
  url: "https://northernwidget.com"

defaults:
  - scope:
      path: ""
    values:
      layout: single
      render_with_liquid: false
      toc: true
      toc_sticky: true
      sidebar:
        nav: api
